### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by METACEO** [maierfelix/nvk#1]
@maierfelix - while I see the window's installation steps, could the documentation include the support (or lack of support) for Linux systems?

**Comment by maierfelix** [comment]
Addressing this now

**Comment by maierfelix** [comment]
[This](https://github.com/maierfelix/nvk/tree/linux) branch now contains the changes to build and run on linux. I successfully ran all examples contained [here](https://github.com/maierfelix/nvk-examples/tree/8d7365d3195ce3b92978b60496041bcabd90e73f). Tested it under Ubuntu 18.04 with NVIDIA 1070 and 415.0 drivers. @METACEO could you checkout the linux branch and approve that it's working?

After checking out the branch, navigate into the examples folder and change the package.json's `nvk` dependency to `file:../`. Then just navigate into an example and run `npm run start --vkversion=1.1.97`

**Comment by maierfelix** [comment]
@METACEO Oh sorry - I tested it successfully on a friends laptop and forgot to update my answer here.

I pushed the linux changes to master and updated the npm package - you now just have to:

Clone the `nvk-examples` repository, do `npm install`, navigate into an example and run `npm run start --vkversion=1.1.97`.

Also make sure you have a decent node.js version (>= 10.9.0 is recommended)

**Comment by maierfelix** [comment]
@METACEO can this be closed?
