### ISSUE TITLE
pNext isn't extended by 'structextends' attribute

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/nvk#10]
With https://github.com/maierfelix/nvk/commit/7637a81a6c500c75a392c8d05da7cd284739a99d there was added type validation when setting a `pNext` struct member. This is now partially broken by not handling the `structextends` attribute in the specification when adding a fix for https://github.com/maierfelix/nvk/issues/7.

When a structure is extended by `structextends` then the allowed `pNext` types should be inherited from this structure.

**Comment by maierfelix** [comment]
@Reon90 I pushed a fix in https://github.com/maierfelix/nvk/commit/787926875355cca5306de2d4b51310224c796716, could you check if it's working now?

**Comment by Reon90** [comment]
@maierfelix yes, was fixed

**Comment by maierfelix** [comment]
Great, thank you!
