### ISSUE TITLE
Use NAPI instead of V8

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/nvk#11]
This would allow users to install nvk without the need to download the SDK and compile the bindings. The need of installing Lunar's Vulkan runtime could also be removed by just shipping the runtime files with the binaries.

Edit: [this](https://github.com/maierfelix/nvk/tree/napi) branch contains all necessary conversions, nearly ready to be merged

**Comment by maierfelix** [comment]
@Reon90 NAPI conversions are landed into master, could you test your RT project if it's still working?

Just clone master and run your example, you don't have to do npm install, the bindings are now pre-compiled

**Comment by Reon90** [comment]
@maierfelix yes it's working.

**Comment by maierfelix** [comment]
great, thank you!
