### ISSUE TITLE
Unable to build on linux

### ISSUE THREAD

**Issue by jleppert** [maierfelix/nvk#16]
The vulkan SDK is installed and I can build all the samples and tools etc. My $VULKAN_SDK env is /home/johnathan/Downloads/1.1.101.0/x86_64.

$ npm run generate --vkversion=1.1.101

> nvk@0.3.5 generate /home/johnathan/nvk
> node --experimental-modules ./generator/index.mjs

(node:10560) ExperimentalWarning: The ESM module loader is experimental.
Generating bindings for 1.1.101...
Generating AST..
Generating Vk structs..
Generating Vk handles..
Warning: Cannot resolve required platform includes for linux
Generating Vk enums..
Generating Vk calls..
Generating Vk includes..
Generating Typescript definition..
Generating binding.gyp..
Warning: Using fallback SDK at /home/johnathan/Downloads/1.1.101.0/x86_64
Generating package.json..
Generating utils..
Generating indices..
Generating typescript index..

Generation stats:
Total files: 0/13
Total size: 8975.878kb
Total lines: 256.549lines
johnathan@johnathan-desktop:~/nvk$ npm run build --vkversion=1.1.101

> nvk@0.3.5 build /home/johnathan/nvk
> node ./build.js

Compiling bindings for version 1.1.101...
Platform: linux | x64
Node: 11.10.1
V8: 7.0.276.38-node.17

Copying files..
Done!

Compiling bindings..
Copying /home/johnathan/Downloads/1.1.101.0/x86_64/lib/libvulkan.so.1.1.97 -> ./generated/1.1.101/linux/build/Release/libvulkan.so.1.1.97
Failed to copy /home/johnathan/Downloads/1.1.101.0/x86_64/lib/libvulkan.so.1.1.97 -> ./generated/1.1.101/linux/build/Release/libvulkan.so.1.1.97

/home/johnathan/nvk/build.js:103
          throw error;
          ^
Error: ENOENT: no such file or directory, lstat '/home/johnathan/Downloads/1.1.101.0/x86_64/lib/libvulkan.so.1.1.97'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvk@0.3.5 build: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nvk@0.3.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/johnathan/.npm/_logs/2019-03-05T11_20_06_504Z-debug.log
johnathan@johnathan-desktop:~/nvk$ make: Entering directory '/home/johnathan/nvk/generated/1.1.101/linux/build'
  CXX(target) Release/obj.target/addon-linux/src/index.o
../src/index.cpp:14:10: fatal error: window.h: No such file or directory
 #include "window.h"
          ^~~~~~~~~~
compilation terminated.
addon-linux.target.mk:126: recipe for target 'Release/obj.target/addon-linux/src/index.o' failed
make: *** [Release/obj.target/addon-linux/src/index.o] Error 1
make: Leaving directory '/home/johnathan/nvk/generated/1.1.101/linux/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/johnathan/.nvm/versions/node/v11.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/home/johnathan/.nvm/versions/node/v11.10.1/bin/node" "/home/johnathan/.nvm/versions/node/v11.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/johnathan/nvk/generated/1.1.101/linux
gyp ERR! node -v v11.10.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
^C

**Comment by maierfelix** [comment]
Didn't cover the latest version yet, will do that soon. Are you able to run the examples with `1.1.97`? You don't have to compile the bindings to be able to use nvk

**Comment by maierfelix** [comment]
Updated project to Vulkan 1.1.101, please check if it's working now
