### ISSUE TITLE
GPGPU example?

### ISSUE THREAD

**Issue by robertleeplummerjr** [maierfelix/nvk#2]
I didn't see this in the documentation, but I'd LOVE to see an example where we don't have to open a new window, and we can just calculate from GPU very very simple math.  If you can do this, we could potentially write a backend/driver for http://gpu.rocks/ .

**Comment by maierfelix** [comment]
A compute shader example is one of my main Todos! I will let you know when I got something up for you.

A good starting point is the Triangle example, just remove the window and graphics stuff and you are ready to try it yourself - It's not enforced to use a window.

Also please note that node-vulkan only runs on desktop, not in the browser - is this a problem for you?

**Comment by robertleeplummerjr** [comment]
>this a problem for you?

GPU.js already has a webgl and webgl2 backend.  We want new backends, ones that are server side GPU centric.


Develop in one language, with one environment, and deploy everywhere.

**Comment by robertleeplummerjr** [comment]
Forgot to mention, gpu.js transpiles on the fly to whatever backends we need.

**Comment by maierfelix** [comment]
@robertleeplummerjr Added [this](https://github.com/maierfelix/node-vulkan/tree/master/examples) compute shader example

**Comment by robertleeplummerjr** [comment]
Consider this closed.  Great job!
