### ISSUE TITLE
Vulkan Memory Allocator bindings?

### ISSUE THREAD

**Issue by helixd-2k18** [maierfelix/nvk#21]
I'm often using VMA for our projects, and still needs VMA in Node.js, so I propose to add Vulkan Memory Allocator (VMA) library into Node.js bindings.

**Comment by maierfelix** [comment]
This should be moved into a separate repository as this one's goal is to just be the entry door from Node to Vulkan.

**Comment by maierfelix** [comment]
@helixd-2k18 can this be closed?

**Comment by helixd-2k18** [comment]
When appear memory allocator bindings for Node, then you can...
