### ISSUE TITLE
Consuming via published npm package 

### ISSUE THREAD

**Issue by avindra** [maierfelix/nvk#24]
I see this on npm:

```
$ npm info nvk

nvk@0.5.3 | MIT | deps: none | versions: 30
Vulkan rendering API for node
https://github.com/maierfelix/nvk#readme

keywords: vulkan, opengl, bindings, 3d, 2d, rendering

dist
.tarball: https://registry.npmjs.org/nvk/-/nvk-0.5.3.tgz
.shasum: 249fda90b7f4ade6b740622e59b9b63715beac27
.integrity: sha512-nySaU9zBQefbvGCyUASNDuJokj2seE+HNRPu93VhBbevfWAONWXhaqeOVDbraBLOTPHdtIEhqJ5rmIc9DeG02Q==
.unpackedSize: 28.5 MB

maintainers:
- maierfelix <maier.felix96@gmail.com>

dist-tags:
latest: 0.5.3  

published 3 days ago by maierfelix <maier.felix96@gmail.com>
```

but is the recommended usage to actually build everything from source? Regular package installation doesn't seem to work

**Comment by maierfelix** [comment]
It is not required to build from source, as the package comes with pre-compiled binaries. If you intend to build from source, then see [this](https://github.com/maierfelix/nvk#build-instructions) section.
A simple `npm install nvk` is enough in most cases, building from source is only required if the bindings get modified

**Comment by avindra** [comment]
thanks for the info. I'm closing the issue for now. 

i shall re-open it once I have some time to test again.

thank you for creating this project btw. even to this day people rip on javascript, but, there is great value in experimentation and JS is quite suitable for this purpose.
