### ISSUE TITLE
TextEncoder is not defined

### ISSUE THREAD

**Issue by pjoe** [maierfelix/nvk#25]
When running on windows with node 10.15, I get error about missing TextEncoder. I solved it temporarily by adding this to interfaces.js:

```js
const {TextEncoder, TextDecoder} = require('util');
```

**Comment by maierfelix** [comment]
This should be fixed with version `0.5.6`, could you approve the changes?
Note that the vulkan version changed from `1.1.101` to `1.1.106`, so make sure to use the `--vkversion=1.1.106` flag from now on

**Comment by pjoe** [comment]
@maierfelix `0.5.6` seems to work a lot better - thanks. No issues with TextEncoder and correctly lists both my GPUs (I'm on Optimus laptop, so both Intel and nVidia).

Closing this issue
