### ISSUE TITLE
In index.d.ts bigint function parameters can't be just numbers

### ISSUE THREAD

**Issue by Taras55** [maierfelix/nvk#27]
to fix this problem in file **generator/generators/typescript.mjs** replace
```
case JavaScriptType.BIGINT: {
    return `bigint`;
}
```
by
```
case JavaScriptType.BIGINT: {
    return `bigint | number`;
}
```

**Comment by BQurious** [comment]
I think this is intended? BigInt isn't compatible with normal numbers

**Comment by Taras55** [comment]
> I think this is intended? BigInt isn't compatible with normal numbers

In C++ code function can take numbers instead bigint, but in d.ts this behavior is not described

**Comment by maierfelix** [comment]
Functions like [vkWaitForFences](https://maierfelix.github.io/nvk/1.1.106/calls/vkWaitForFences.html) take a BigInt, but in many cases a Number is enough. Before adding this polymorphism, only BigInt was allowed, but this negatively affected code quality.

Both `uint64_t` and `size_t` allow using a BigInt _and_ Number.

@Taras55 I will fix your issues soon

**Comment by maierfelix** [comment]
Expecting this to be solved
