### ISSUE TITLE
Typescript: Import name shouldn't require a platform name

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/nvk#30]
Importing nvk shouldn't require to put the platform into the import name as shown [here](https://github.com/maierfelix/nvk-examples/blob/7d7356c11669f302c63ef4c9c5c62dc2f4a0a83a/typescript/index.ts#L1).

**Comment by zeeshan595** [comment]
This might help a bit https://github.com/zeeshan595/nvk-boilerplate

**Comment by maierfelix** [comment]
Nice one! Unfortunately I'm not really a typescript user, would you mind adding your code to this project?

**Comment by zeeshan595** [comment]
That should resolve the issue, just make sure to update `platform.ts` imports.
Or can create a symlink that updates when new files are generated.
Not sure how windows handles symlinks though.
https://github.com/maierfelix/nvk/pull/32
