### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by whaqzhzd** [maierfelix/nvk#4]
I encountered this problem during the compilation process. Is there any way to solve it?
![image](https://user-images.githubusercontent.com/16913061/51456911-52999500-1d8a-11e9-92ed-e62c88177dea.png)

**Comment by maierfelix** [comment]
Where did you install Vulkan SDK?

**Comment by whaqzhzd** [comment]
I am installing at C:\VulkanSDK\1.91.91

**Comment by whaqzhzd** [comment]
Is my version wrong?

**Comment by maierfelix** [comment]
Yes, sub-versions are not supported yet because there is inconsistency with the SDK versions. Try using the recommended version of the installer which is `1.1.85`

**Comment by maierfelix** [comment]
https://github.com/maierfelix/nvk/issues/3

**Comment by whaqzhzd** [comment]
I reinstalled 1.1.85. Now the compilation is successful, thank you for your outstanding project.
