### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Reon90** [maierfelix/nvk#5]
npm run build --vkversion=1.1.97 --msvsversion=2017

nvk\generated\1.1.97\src\enums.h(1869): error C2059: syntax error: 'bad suffix on number' [nvk\generated\1.1.97\build\addon.vcxproj]
nvk\generated\1.1.97\src\enums.h(1869): error C2153: integer literals must have at least one digit [nvk\generated\1.1.97\build\addon.vcxproj]

1.1.85 bulds correctly.

**Comment by maierfelix** [comment]
I didn't update the npm package yet, but the last commit in master includes support for 1.1.97.

**Comment by maierfelix** [comment]
Updated the npm package to `v0.1.8` with commit https://github.com/maierfelix/nvk/commit/67ebc2b75f2c6beb20429af233bc0e838cf99ad7
If you got some time, then please approve that `1.1.97` is now working for you

**Comment by Reon90** [comment]
@maierfelix was fixed
