### ISSUE TITLE
[WebAssembly, ArrayBuffer] Low-level input for structs?

### ISSUE THREAD

**Issue by helixd-2k18** [maierfelix/nvk#51]
I want to propose low-level structured `ArrayBuffer` observing. Why it needs? It may more usable with WebAssembly applications, more directly... (fore example, AssemblyScript language). The same rule applicable for `Shared` memory types. 

```typescript
let arrayBuffer: ArrayBuffer = new ArrayBuffer(VkInstanceCreateInfo.sizeof); // static .sizeof 
let instanceInfo: VkInstanceCreateInfo = new VkInstanceCreateInfo(arrayBuffer); // but just observe, NOT copy
```

**Comment by maierfelix** [comment]
This is already possible:
````ts
let buf: ArrayBuffer = new ArrayBuffer(VkInstanceCreateInfo.byteLength);
let instanceInfo: VkInstanceCreateInfo = new VkInstanceCreateInfo({
  $memoryBuffer: buf,
  $memoryOffset: 0x0
});
````

I've added this when adding support for sub-structures - e.g. [VkRect2D](https://maierfelix.github.io/nvk/1.1.126/structs/VkRect2D.html), where `offset` and `extent` are `VkOffset2D` structs using the same memory as `VkRect2D`, but with a different offset.

You can check the *Default Properties* section in the docs, for example [here](https://maierfelix.github.io/nvk/1.1.126/structs/VkInstanceCreateInfo.html), which shows the underlying methods and properties for low-level access.

What you're probably most interested in are the `$memoryBuffer` and `$memoryOffset` properties and the `reflect` method, which synchronizes the JS Object with the ArrayBuffer.

Structs also come with a `memoryLayout` object, which describes the byteOffset and byteLength of each struct member, e.g.:
````js

VkInstanceCreateInfo.byteLength = 0x40;
VkInstanceCreateInfo.memoryLayout = {
  sType: {
    byteOffset: 0x0,
    byteLength: 0x4
  },
  pNext: {
    byteOffset: 0x8,
    byteLength: 0x8
  },
  ...
};
````

Also, if you're interested about how *nvk* works internally, checkout [this](https://gist.github.com/maierfelix/f35b54d19a3c56f60a80be2ac32893db) file.

**Comment by helixd-2k18** [comment]
I'm getting some skills and experience for professional purposes. Just interesting how work these worlds together. So, I trying to combine NVK with AssemblyScript (and run from that script language)…

**Comment by maierfelix** [comment]
*nvk* extends the ArrayBuffer Object with additional low-level methods - see the docs [here](https://maierfelix.github.io/nvk/1.1.126/additional/ArrayBuffer.html)

Note that one minor problem with Wasm is that it is in a fixed 32bit world, while NAPI is 64bit, so when you fill a Vulkan struct in Wasm, the memory doesn't align correctly.

I don't know your Wasm setup, but you might do it like this (pseudo code):

Setup:
````js
let heap = new ArrayBuffer(2<<15);
let heapU32 = new Uint32Array(heap);
let module = new WebAssembly.Module(buffer);
let instance = new WebAssembly.Instance(module);
````

In C or AssemblyScript:
````C
int test() {
  VkInstanceCreateInfo* info = (VkInstanceCreateInfo*) malloc(sizeof(VkInstanceCreateInfo));
  return (int) info;
}
````

In JS:
````js
let infoAddr = instance.test();
let infoAddrView = new VkInstanceCreateInfo({
  $memoryBuffer: heap,
  $memoryOffset: infoAddr
});
````

**Comment by helixd-2k18** [comment]
I already tried to use with AssemblyScript and custom methods (with structure's). I found some critical bugs when create `VkInstanceCreateInfo` from WebAssembly memory with offset: no extension layers lists, application crash with that structure. I checked alignment, but has correct. Probably, there is internal "get" and "set" issues.
