### ISSUE TITLE
Validation Layer name change to "VK_LAYER_KHRONOS_validation"

### ISSUE THREAD

**Issue by charles-lunarg** [maierfelix/nvk#53]
VK_LAYER_LUNARG_standard_validation was deprecated in favor of VK_LAYER_KHRONOS_validation. 
While they both have the same functionality (as its the same code under the hood) the former was re-architected to have less overhead, and VK_LAYER_LUNARG_standard_validation will be removed in a future SDK version.

**Comment by maierfelix** [comment]
I'm not sure what you're referring to, this project doesn't make use of the validation layers itself, it's up to the user. Please reopen this if you feel like this was a mistake

**Comment by charles-lunarg** [comment]
I see my mistake now, I didn't note that it was the README.md which has the issue, not the project itself. You are very right, the project makes validation layers a user done option. If this project targets SDK versions 1.1.121 or later, I would suggest updating the readme.

**Comment by maierfelix** [comment]
Thanks for spotting this, I've updated the readme

**Comment by charles-lunarg** [comment]
No problem, and apologies for not making that clear in the issue post. I momentarily forgot other people can't read my mind it seems.
