### ISSUE TITLE
Polymorphic arguments for struct aliases

### ISSUE THREAD

**Issue by Reon90** [maierfelix/nvk#7]
I don't understand why memoryRequirements in VkMemoryRequirements2 object is NULL, on the other hand c++ realization is correct.

nvk - JS
![annotation 2019-01-30 114435](https://user-images.githubusercontent.com/8707222/51969140-b60b7d00-2484-11e9-9e51-bb848da348f0.jpg)

C++
![annotation 2019-01-30 114352](https://user-images.githubusercontent.com/8707222/51969157-c02d7b80-2484-11e9-9d5b-a127d0db2623.jpg)

**Comment by maierfelix** [comment]
I can approve that this is not working as expected, I found the following reason:

`vkGetAccelerationStructureMemoryRequirementsNV` takes `VkMemoryRequirements2KHR` which is an alias for `VkMemoryRequirements2`. `VkMemoryRequirements2KHR` doesn't contain any members, so the JS->Type reflection [here](https://github.com/maierfelix/nvk/blob/master/generated/1.1.97/src/calls.h#L15054-L15058) is not performed at all.

The following line in the `1.1.97` XML specification indicates, that:
````xml
<type category="struct" name="VkMemoryRequirements2KHR" alias="VkMemoryRequirements2"/>
````

Note the `alias` attribute. This could be solved by interpreting `VkMemoryRequirements2KHR` as `VkMemoryRequirements2` in the parsing process and in the code-generation part as well. I'm not a 100% sure though if this is a general fix.

**Comment by Reon90** [comment]
@maierfelix are you planning to implement it?

**Comment by Reon90** [comment]
@maierfelix no sorry I don't have, as you know I can't build basic example with RT.
any news about it?

**Comment by maierfelix** [comment]
@Reon90 Latest master now contains the changes to fix this issue, please validate that it's working now.
I also added parameter type validation for vulkan function calls, they should now be more safe to use.

I guess that you use `vkGetAccelerationStructureMemoryRequirementsNV` to gather the memoryRequirements - Please note that the specification currently states to use `VkMemoryRequirements2KHR` for `pMemoryRequirements` and not `VkMemoryRequirements2`.

`VkMemoryRequirements2KHR` is just a *typedef* for `VkMemoryRequirements2`, so please use this one as described in the documentation [here](https://maierfelix.github.io/nvk/1.1.97/calls/vkGetAccelerationStructureMemoryRequirementsNV.html)

**Comment by Reon90** [comment]
@maierfelix thank you very much, I got correct results.

**Comment by maierfelix** [comment]
I will close this issue as soon as this is fully resolved (e.g. both `VkMemoryRequirements2` and `VkMemoryRequirements2KHR` are allowed as `pMemoryRequirements`)

**Comment by Reon90** [comment]
@maierfelix 
```
const descriptorIndexing = new VkPhysicalDeviceDescriptorIndexingFeaturesEXT();
const deviceFeatures = new VkPhysicalDeviceFeatures2();
deviceFeatures.pNext = descriptorIndexing;
vkGetPhysicalDeviceFeatures2(physicalDevice, deviceFeatures);
```
TypeError: 'VkPhysicalDeviceFeatures2.pNext' must be 'null'

**Comment by maierfelix** [comment]
I can approve that this isn't working, I'm investigating

**Comment by maierfelix** [comment]
Closing this as this is not an too important issue? If someone is actually in the need to get this implemented, I'm open to make the changes

**Comment by maierfelix** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/issues/1122
