### ISSUE TITLE
vkGetAccelerationStructureHandleNV pData is NULL

### ISSUE THREAD

**Issue by Reon90** [maierfelix/nvk#8]
```
VUID-vkGetAccelerationStructureHandleNV-pData-parameter(ERROR / SPEC): msgNum: 0 - vkGetAccelerationStructureHandleNV: required parameter pData specified as NULL. The Vulkan spec states: pData must be a valid pointer to an array of dataSize bytes (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkGetAccelerationStructureHandleNV-pData-parameter)
    Objects: 1
        [0] 0, type: 0, name: NULL
```
According to spec, pData is a pointer to a user-allocated buffer where the results will be written.
I checked call.h and found that it's always NULL.

**Comment by maierfelix** [comment]
Hey I pushed some changes which now uses `ArrayBuffers` for `void *` and `const void *` types, both for structs and calls, could you check?

I found [this](https://github.com/DsoTsin/VulkanRTX) RT example, are you using this as reference?
Also found [this](https://github.com/DsoTsin/VulkanRTX/blob/489e62d751b1e8069f8f9ab78671cc9aab0cc147/Source/02_AccelerationStructure/02_AccelerationStructure.cpp#L216-L222) part, which maps memory of a user-defined structure - you could create such a structure yourself using an `ArrayBuffer` - I have uploaded [this](https://jsfiddle.net/5tz0hsjq/) simple example on how you could do this

**Comment by Reon90** [comment]
@maierfelix thank you, it was fixed.
No, I use another, but thank you, it's useful link.

**Comment by maierfelix** [comment]
Thanks for the feedback, considering this closed
